
export const videos = [
    {
        id: 1,
        title: "How to Cook the Perfect Steak",
        url: "https://example.com/videos/abc123",
        thumbnailUrl: "/2.png",
        userId: "user789",
        uploadDate: new Date("2024-12-14T10:15:30.000Z"),
        description: "Learn the secrets to cooking the perfect steak every time with this step-by-step guide!",
        views: 10500,
        likes: 800,
        tags: ["cooking", "steak", "recipe", "food"],
        artists: ["user789"],
        duration: 600,
        comments: 120,
        isPublic: true,
        released: true,
    },
    {
        id: 2,
        title: "The Ultimate JavaScript Tutorial for Beginners for Beginners for bruh for Beginners for Beginners for Beginners",
        url: "https://example.com/videos/def456",
        thumbnailUrl: "/3.png",
        userId: "user456",
        uploadDate: new Date("2024-12-12T08:45:00.000Z"),
        description: "Master JavaScript with this comprehensive tutorial designed for beginners.",
        views: 45000,
        likes: 3200,
        tags: ["programming", "javascript", "tutorial", "coding"],
        artists: ["user456"],
        duration: 521,
        comments: 250,
        isPublic: true,
        released: true,
    },
    {
        id: 3,
        title: "10 Minute Yoga for Stress Relief",
        url: "https://example.com/videos/ghi789",
        thumbnailUrl: "/1.png",
        userId: "user123",
        uploadDate: new Date("2024-12-10T07:30:15.000Z"),
        description: "A quick yoga routine to help you relax and reduce stress in just 10 minutes.",
        views: 23000,
        likes: 1800,
        tags: ["yoga", "wellness", "stress relief", "fitness"],
        artists: ["user123"],
        duration: 600,
        comments: 90,
        isPublic: true,
        released: true,
    },
    {
        id: 4,
        title: "Exploring the Hidden Gems of Iceland",
        url: "https://example.com/videos/jkl012",
        thumbnailUrl: "/5.png",
        userId: "user321",
        uploadDate: new Date("2024-12-09T18:00:00.000Z"),
        description: "Join us on an adventure through the lesser-known but breathtaking locations in Iceland.",
        views: 15000,
        likes: 1200,
        tags: ["travel", "iceland", "adventure", "nature"],
        artists: ["user321"],
        duration: 1800,
        comments: 75,
        isPublic: true,
        released: true,
    },
    {
        id: 5,
        title: "Top 5 Gadgets You Need in 2024",
        url: "https://example.com/videos/mno345",
        thumbnailUrl: "/4.png",
        userId: "user654",
        uploadDate: new Date("2024-12-08T14:20:45.000Z"),
        description: "Discover the top 5 must-have gadgets for the year 2024!",
        views: 38000,
        likes: 2900,
        tags: ["gadgets", "tech", "reviews", "2024"],
        artists: ["user654"],
        duration: 900,
        comments: 200,
        isPublic: false,
        released: true,
    },
    {
        id: 6,
        title: "How to Cook the Perfect Steak",
        url: "https://example.com/videos/abc123",
        thumbnailUrl: "/2.png",
        userId: "user789",
        uploadDate: new Date("2024-12-14T10:15:30.000Z"),
        description: "Learn the secrets to cooking the perfect steak every time with this step-by-step guide!",
        views: 10500,
        likes: 800,
        tags: ["cooking", "steak", "recipe", "food"],
        artists: ["user789"],
        duration: 600,
        comments: 120,
        isPublic: true,
        released: true,
    },
    {
        id: 7,
        title: "The Ultimate JavaScript Tutorial for Beginners",
        url: "https://example.com/videos/def456",
        thumbnailUrl: "/3.png",
        userId: "user456",
        uploadDate: new Date("2024-12-12T08:45:00.000Z"),
        description: "Master JavaScript with this comprehensive tutorial designed for beginners.",
        views: 45000,
        likes: 3200,
        tags: ["programming", "javascript", "tutorial", "coding"],
        artists: ["user456"],
        duration: 5400,
        comments: 250,
        isPublic: true,
        released: true,
    },
    {
        id: 8,
        title: "5 Minute Yoga for Stress Relief",
        url: "https://example.com/videos/ghi789",
        thumbnailUrl: "/1.png",
        userId: "user123",
        uploadDate: new Date("2024-12-10T07:30:15.000Z"),
        description: "A quick yoga routine to help you relax and reduce stress in just 10 minutes.",
        views: 23000,
        likes: 1800,
        tags: ["yoga", "wellness", "stress relief", "fitness"],
        artists: ["user123"],
        duration: 6700,
        comments: 90,
        isPublic: true,
        released: true,
    },
    {
        id: 9,
        title: "Exploring the Hidden Gems of Iceland",
        url: "https://example.com/videos/jkl012",
        thumbnailUrl: "/1.png",
        userId: "user321",
        uploadDate: new Date("2024-12-09T18:00:00.000Z"),
        description: "Join us on an adventure through the lesser-known but breathtaking locations in Iceland.",
        views: 15000,
        likes: 1200,
        tags: ["travel", "iceland", "adventure", "nature"],
        artists: ["user321"],
        duration: 1800,
        comments: 75,
        isPublic: true,
        released: true,
    },
    {
        id: 10,
        title: "Top 5 Gadgets You Need in 2024",
        url: "https://example.com/videos/mno345",
        thumbnailUrl: "/2.png",
        userId: "user654",
        uploadDate: new Date("2024-12-08T14:20:45.000Z"),
        description: "Discover the top 5 must-have gadgets for the year 2024!",
        views: 38000,
        likes: 2900,
        tags: ["gadgets", "tech", "reviews", "2024"],
        artists: ["user654"],
        duration: 900,
        comments: 200,
        isPublic: false,
        released: true,
    },
    {
        id: 11,
        title: "How to Cook the Perfect Steak",
        url: "https://example.com/videos/abc123",
        thumbnailUrl: "/4.png",
        userId: "user789",
        uploadDate: new Date("2024-12-14T10:15:30.000Z"),
        description: "Learn the secrets to cooking the perfect steak every time with this step-by-step guide!",
        views: 10500,
        likes: 800,
        tags: ["cooking", "steak", "recipe", "food"],
        artists: ["user789"],
        duration: 600,
        comments: 120,
        isPublic: true,
        released: true,
    },
    {
        id: 12,
        title: "The Ultimate JavaScript Tutorial for Beginners for Beginners for bruh for Beginners for Beginners for Beginners",
        url: "https://example.com/videos/def456",
        thumbnailUrl: "/5.png",
        userId: "user456",
        uploadDate: new Date("2024-12-12T08:45:00.000Z"),
        description: "Master JavaScript with this comprehensive tutorial designed for beginners.",
        views: 45000,
        likes: 3200,
        tags: ["programming", "javascript", "tutorial", "coding"],
        artists: ["user456"],
        duration: 521,
        comments: 250,
        isPublic: true,
        released: true,
    },
    {
        id: 13,
        title: "10 Minute Yoga for Stress Relief",
        url: "https://example.com/videos/ghi789",
        thumbnailUrl: "/1.png",
        userId: "user123",
        uploadDate: new Date("2024-12-10T07:30:15.000Z"),
        description: "A quick yoga routine to help you relax and reduce stress in just 10 minutes.",
        views: 23000,
        likes: 1800,
        tags: ["yoga", "wellness", "stress relief", "fitness"],
        artists: ["user123"],
        duration: 600,
        comments: 90,
        isPublic: true,
        released: true,
    },
    {
        id: 14,
        title: "Exploring the Hidden Gems of Iceland",
        url: "https://example.com/videos/jkl012",
        thumbnailUrl: "/1.png",
        userId: "user321",
        uploadDate: new Date("2024-12-09T18:00:00.000Z"),
        description: "Join us on an adventure through the lesser-known but breathtaking locations in Iceland.",
        views: 15000,
        likes: 1200,
        tags: ["travel", "iceland", "adventure", "nature"],
        artists: ["user321"],
        duration: 1800,
        comments: 75,
        isPublic: true,
        released: true,
    },
    {
        id: 15,
        title: "Top 5 Gadgets You Need in 2024",
        url: "https://example.com/videos/mno345",
        thumbnailUrl: "/5.png",
        userId: "user654",
        uploadDate: new Date("2024-12-08T14:20:45.000Z"),
        description: "Discover the top 5 must-have gadgets for the year 2024!",
        views: 38000,
        likes: 2900,
        tags: ["gadgets", "tech", "reviews", "2024"],
        artists: ["user654"],
        duration: 900,
        comments: 200,
        isPublic: false,
        released: true,
    },
    {
        id: 16,
        title: "How to Cook the Perfect Steak",
        url: "https://example.com/videos/abc123",
        thumbnailUrl: "/4.png",
        userId: "user789",
        uploadDate: new Date("2024-12-14T10:15:30.000Z"),
        description: "Learn the secrets to cooking the perfect steak every time with this step-by-step guide!",
        views: 10500,
        likes: 800,
        tags: ["cooking", "steak", "recipe", "food"],
        artists: ["user789"],
        duration: 600,
        comments: 120,
        isPublic: true,
        released: true,
    },
    {
        id: 17,
        title: "The Ultimate JavaScript Tutorial for Beginners",
        url: "https://example.com/videos/def456",
        thumbnailUrl: "/3.png",
        userId: "user456",
        uploadDate: new Date("2024-12-12T08:45:00.000Z"),
        description: "Master JavaScript with this comprehensive tutorial designed for beginners.",
        views: 45000,
        likes: 3200,
        tags: ["programming", "javascript", "tutorial", "coding"],
        artists: ["user456"],
        duration: 5400,
        comments: 250,
        isPublic: true,
        released: true,
    },
    {
        id: 18,
        title: "5 Minute Yoga for Stress Relief",
        url: "https://example.com/videos/ghi789",
        thumbnailUrl: "/1.png",
        userId: "user123",
        uploadDate: new Date("2024-12-10T07:30:15.000Z"),
        description: "A quick yoga routine to help you relax and reduce stress in just 10 minutes.",
        views: 23000,
        likes: 1800,
        tags: ["yoga", "wellness", "stress relief", "fitness"],
        artists: ["user123"],
        duration: 6700,
        comments: 90,
        isPublic: true,
        released: true,
    },
    {
        id: 19,
        title: "Exploring the Hidden Gems of Iceland",
        url: "https://example.com/videos/jkl012",
        thumbnailUrl: "/2.png",
        userId: "user321",
        uploadDate: new Date("2024-12-09T18:00:00.000Z"),
        description: "Join us on an adventure through the lesser-known but breathtaking locations in Iceland.",
        views: 15000,
        likes: 1200,
        tags: ["travel", "iceland", "adventure", "nature"],
        artists: ["user321"],
        duration: 1800,
        comments: 75,
        isPublic: true,
        released: true,
    },
    {
        id: 20,
        title: "Top 5 Gadgets You Need in 2024",
        url: "https://example.com/videos/mno345",
        thumbnailUrl: "/1.png",
        userId: "user654",
        uploadDate: new Date("2024-12-08T14:20:45.000Z"),
        description: "Discover the top 5 must-have gadgets for the year 2024!",
        views: 38000,
        likes: 2900,
        tags: ["gadgets", "tech", "reviews", "2024"],
        artists: ["user654"],
        duration: 900,
        comments: 200,
        isPublic: false,
        released: true,
    },
];
