import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { VideoNavbar } from "@/components/Navbar/VideoNavbar";
import { TanstackProvider } from "@/components/providers/tanstack-provider";
import { Toaster } from "react-hot-toast";
import { headers } from "next/headers";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900"
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900"
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default async function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    const head = headers();

    const serverSignedIn = (await head).get("x-is-logged-in");
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen min-w-screen`}
            >
                <TanstackProvider>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <div className="flex flex-col w-full font-[family-name:var(--font-geist-sans)] h-screen">
                            <VideoNavbar
                                serverSignedIn={serverSignedIn === "true"}
                            />
                            {children}
                            <Toaster />
                        </div>
                    </ThemeProvider>
                </TanstackProvider>
            </body>
        </html>
    );
}
